# ── サイト基本設定（config.toml） ──
# baseURL、言語コード、テーマ、ページネーションなど

baseurl = "https://t-shinju.github.io/graphics-beginning"
languageCode = "ja"
title = "グラフィックスことはじめ"

# 多言語設定を用いる場合にデフォルト(URLに言語パスがつかない)となる言語
defaultContentLanguage = "ja"

# CJK（中国語・日本語・韓国語）向けに文字カウント等を適切に処理するか
hasCJKLanguage = true

[pagination]
# ページ切り替えリンクの最大表示数(1, 2, 3, 4, 5, ...となる)
pagerSize = 5