# ── メニュー設定（menu.toml） ──
# サイト内ナビゲーション（main）とSNSリンク（social）を定義

#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# ── ソーシャルリンク設定 ──
# GitHub アカウントへのリンク
[[social]]
identifier = "github"                       # 内部識別子（他と重複しないユニークな値）
name       = "GitHub"                       # ホバー時に表示されるテキスト
url        = "https://github.com/t-shinju"  # クリック先の URL
[social.params]
icon    = "brand-github" # テーマが対応するアイコン名
newtab  = true           # true にすると別タブで開く

# X（旧 Twitter）アカウントへのリンク
[[social]]
identifier = "twitter"
name       = "X"
url        = "https://x.com/new_heavy"
[social.params]
icon    = "brand-twitter"
newtab  = true
